
POST http://localhost:3003/users
Content-Type: application/json

{   
    "name": "José",
    "email": "jose@email.com",
    "password": "jose456"
}

###
GET http://localhost:3003/users
Content-Type: application/json

###
POST http://localhost:3003/products
Content-Type: application/json

{   
    "name": "Airpods",
    "price": 950,
    "image_url": "https://imgs.casasbahia.com.br/12731485/1xg.jpg?imwidth=500"
}

###
GET http://localhost:3003/products?order=asc&search=air
Content-Type: application/json

###
POST http://localhost:3003/purchases
Content-Type: application/json

{   
    "user_id": "1",
    "product_id": "3",
    "quantity": 1
}

###
GET http://localhost:3003/users/4/purchases
Content-Type: application/json

###
GET http://localhost:3003/usersModified
Content-Type: application/json